package ch.welld.schindler.fixture.droolsknowledge.components.loppanel;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LopPanelConfiguration implements Serializable {

    static final long serialVersionUID = 1L;

    private Boolean withGlass;
    private Boolean withLogo;
    private String decoPanel;
    private String buttonPanel;

    public LopPanelConfiguration() {
    }

    public Boolean getWithGlass() {
        return this.withGlass;
    }

    public void setWithGlass(Boolean withGlass) {
        this.withGlass = withGlass;
    }

    public Boolean getWithLogo() {
        return this.withLogo;
    }

    public void setWithLogo(Boolean withLogo) {
        this.withLogo = withLogo;
    }

    public String getDecoPanel() {
        return this.decoPanel;
    }

    public void setDecoPanel(String decoPanel) {
        this.decoPanel = decoPanel;
    }

    public String getButtonPanel() {
        return this.buttonPanel;
    }

    public void setButtonPanel(String buttonPanel) {
        this.buttonPanel = buttonPanel;
    }

    public LopPanelConfiguration(Boolean withGlass,
                                 Boolean withLogo, String decoPanel,
                                 String buttonPanel) {
        this.withGlass = withGlass;
        this.withLogo = withLogo;
        this.decoPanel = decoPanel;
        this.buttonPanel = buttonPanel;
    }

}