package ch.welld.schindler.fixtureapp.droolsknowledge.components.lamps;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LampConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean en8120;

	private java.lang.String lamp;

	private java.lang.Boolean na;

	public LampConfiguration() {
	}

	public java.lang.Boolean getEn8120() {
		return this.en8120;
	}

	public void setEn8120(java.lang.Boolean en8120) {
		this.en8120 = en8120;
	}

	public java.lang.String getLamp() {
		return this.lamp;
	}

	public void setLamp(java.lang.String lamp) {
		this.lamp = lamp;
	}

	public java.lang.Boolean getNa() {
		return this.na;
	}

	public void setNa(java.lang.Boolean na) {
		this.na = na;
	}

	public LampConfiguration(java.lang.Boolean en8120, java.lang.String lamp,
			java.lang.Boolean na) {
		this.en8120 = en8120;
		this.lamp = lamp;
		this.na = na;
	}

}