package ch.welld.schindler.fixture.droolsknowledge.components.lamps;

import ch.welld.schindler.fixture.droolsknowledge.materials.CableRequest;
import ch.welld.schindler.fixture.droolsknowledge.components.NullableBoolean;

rule "DT Lamps"
    when
        LampConfiguration( fixtureFamily == "DT" )
    then
end

rule "AT Lamps"
    when
        LampConfiguration( fixtureFamily == "AT" )
    then
end

rule "MT Lamps"
    when
        LampConfiguration( fixtureFamily == "MT" )
    then
end

rule "GST Lamps"
    when
        LampConfiguration( fixtureFamily == "GST" )
    then
end

rule "LARC LAGC Lamp Cables"
    when
        LampConfiguration( lamp in ( "LARC-Communication", "LARC-Phone", "LAGC" ) ) or CableRequest()
    then
end

rule "LARC LAGC Intercom Lamp Cables" extends "LARC LAGC Lamp Cables"
    when
        LampConfiguration( copIntercomStation == NullableBoolean.YES ) or CableRequest()
    then
end

rule "LARC LAGC Not Intercom Lamp Cables" extends "LARC LAGC Lamp Cables"
    when
        LampConfiguration( copIntercomStation == NullableBoolean.NO ) or CableRequest()
    then
end

rule "Other Lamps Cables"
    when
        LampConfiguration( lamp not in ( "LARC-Communication", "LARC-Phone", "LAGC" ) ) or CableRequest()
    then
end