package com.myspace.fixture;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Material implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("materialCode")
	private java.lang.String materialCode;
	@org.kie.api.definition.type.Label("familyCode")
	private java.lang.String familyCode;

	public Material() {
	}

	public java.lang.String getMaterialCode() {
		return this.materialCode;
	}

	public void setMaterialCode(java.lang.String materialCode) {
		this.materialCode = materialCode;
	}

	public java.lang.String getFamilyCode() {
		return this.familyCode;
	}

	public void setFamilyCode(java.lang.String familyCode) {
		this.familyCode = familyCode;
	}

	public Material(java.lang.String materialCode, java.lang.String familyCode) {
		this.materialCode = materialCode;
		this.familyCode = familyCode;
	}

}