package ch.welld.schindler.fixture.droolsknowledge.components.ksindicators;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KSIndicatorConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String color;

	public KSIndicatorConfiguration() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public KSIndicatorConfiguration(java.lang.String type,
			java.lang.String color) {
		this.type = type;
		this.color = color;
	}

}