package ch.welld.schindler.fixture.droolsknowledge.components.controldevices;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;

import java.util.List;
import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class ControlDeviceConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private java.lang.String version;

	private java.lang.String type;

	private Map<String, List<PositionSetup>> positions;

	public ControlDeviceConfiguration() {
	}

	public List<PositionSetup> getPositionsByType(String type) {
		return positions == null ? null : positions.get(type);
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Map<String, List<PositionSetup>> getPositions() {
		return this.positions;
	}

	public void setPositions(
			Map<String, List<PositionSetup>> positions) {
		this.positions = positions;
	}

	public ControlDeviceConfiguration(
			java.lang.String version,
			java.lang.String type,
			Map<String, List<PositionSetup>> positions) {
		this.version = version;
		this.type = type;
		this.positions = positions;
	}

}