package ch.welld.schindler.fixture.droolsknowledge.components.controldevices;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ControlDeviceConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private java.lang.String boxType;
	private java.lang.String cable;

	public ControlDeviceConfiguration() {
	}

	public java.lang.String getBoxType() {
		return this.boxType;
	}

	public void setBoxType(java.lang.String boxType) {
		this.boxType = boxType;
	}

	public java.lang.String getCable() {
		return this.cable;
	}

	public void setCable(java.lang.String cable) {
		this.cable = cable;
	}

	public ControlDeviceConfiguration(java.lang.String boxType,
			java.lang.String cable) {
		this.boxType = boxType;
		this.cable = cable;
	}

}