package ch.welld.schindler.fixture.droolsknowledge.components.controldevices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PositionSetup implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String position;
    private java.lang.String engraving;

    public PositionSetup() {
    }

    public java.lang.String getPosition() {
        return this.position;
    }

    public void setPosition(java.lang.String position) {
        this.position = position;
    }

    public java.lang.String getEngraving() {
        return this.engraving;
    }

    public void setEngraving(java.lang.String engraving) {
        this.engraving = engraving;
    }

    public PositionSetup(java.lang.String position, java.lang.String engraving) {
        this.position = position;
        this.engraving = engraving;
    }

}