package com.myspace.buzzers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BuzzerConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String buzzerType;

	public BuzzerConfiguration() {
	}

	public java.lang.String getBuzzerType() {
		return this.buzzerType;
	}

	public void setBuzzerType(java.lang.String buzzerType) {
		this.buzzerType = buzzerType;
	}

	public BuzzerConfiguration(java.lang.String buzzerType) {
		this.buzzerType = buzzerType;
	}

}