package ch.welld.schindler.fixture.droolsknowledge.components.keyswitches;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeySwitchConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String keyType;
	private java.lang.String keySwitch;
	private java.lang.String keyFunction;

	public KeySwitchConfiguration() {
	}

	public java.lang.String getKeyType() {
		return this.keyType;
	}

	public void setKeyType(java.lang.String keyType) {
		this.keyType = keyType;
	}

	public java.lang.String getKeySwitch() {
		return this.keySwitch;
	}

	public void setKeySwitch(java.lang.String keySwitch) {
		this.keySwitch = keySwitch;
	}

	public java.lang.String getKeyFunction() {
		return this.keyFunction;
	}

	public void setKeyFunction(java.lang.String keyFunction) {
		this.keyFunction = keyFunction;
	}

	public KeySwitchConfiguration(java.lang.String keyType,
			java.lang.String keySwitch, java.lang.String keyFunction) {
		this.keyType = keyType;
		this.keySwitch = keySwitch;
		this.keyFunction = keyFunction;
	}

}