package ch.welld.schindler.fixture.droolsknowledge.components.keyswitches;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeySwitchConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private java.lang.String keyType;
	private java.lang.String keySwitch;
	private java.lang.String keyFunction;

	private java.lang.String engraving;

	public KeySwitchConfiguration() {
	}

	public java.lang.String getKeyType() {
		return this.keyType;
	}

	public void setKeyType(java.lang.String keyType) {
		this.keyType = keyType;
	}

	public java.lang.String getKeySwitch() {
		return this.keySwitch;
	}

	public void setKeySwitch(java.lang.String keySwitch) {
		this.keySwitch = keySwitch;
	}

	public java.lang.String getKeyFunction() {
		return this.keyFunction;
	}

	public void setKeyFunction(java.lang.String keyFunction) {
		this.keyFunction = keyFunction;
	}

	public java.lang.String getEngraving() {
		return this.engraving;
	}

	public void setEngraving(java.lang.String engraving) {
		this.engraving = engraving;
	}

	public KeySwitchConfiguration(java.lang.String keyType,
								  java.lang.String keySwitch, java.lang.String keyFunction,
								  java.lang.String engraving) {
		this.keyType = keyType;
		this.keySwitch = keySwitch;
		this.keyFunction = keyFunction;
		this.engraving = engraving;
	}

}