package com.myspace.fixture.button;

rule "DT2 Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT2" )
    then
end

rule "DT4 Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT4" )
    then
end

rule "DT8 Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT8" )
    then
end

rule "DT4 Push Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT4", fixtureType in ( "PUSH_DOOR", "PUSH_FLOOR" ) )
    then
end

rule "DT4 Push Main Floor Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT4", fixtureType == "PUSH_MAIN" )
    then
end

rule "DT4 Alarm Buttons"
    when
        ButtonConfiguration( fixtureFamily == "DT4", fixtureType == "ALARM" )
    then
end