package ch.welld.schindler.fixture.droolsknowledge.components.buzzers;

rule "DT Buzzers"
    when
        BuzzerConfiguration( fixtureFamily == "DT" )
    then
end

rule "AT Buzzers"
    when
        BuzzerConfiguration( fixtureFamily == "AT" )
    then
end

rule "MT Buzzers"
    when
        BuzzerConfiguration( fixtureFamily == "MT" )
    then
end

rule "GST Buzzers"
    when
        BuzzerConfiguration( fixtureFamily == "GST" )
    then
end
