package ch.welld.schindler.fixtureapp.droolsknowledge.components.fixtures;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FixtureConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("backlight")
	private java.lang.Boolean backlight;
	@org.kie.api.definition.type.Label("buttonColor")
	private java.lang.String buttonColor;

	@org.kie.api.definition.type.Label("fixtureFamily")
	private java.lang.String fixtureFamily;

	@org.kie.api.definition.type.Label("fixtureType")
	private java.lang.String fixtureType;

	@org.kie.api.definition.type.Label("hairlineInsert")
	private java.lang.Boolean hairlineInsert;

	@org.kie.api.definition.type.Label("letterRaised")
	private java.lang.Boolean letterRaised;

	@org.kie.api.definition.type.Label("braille")
	private java.lang.Boolean braille;

	@org.kie.api.definition.type.Label("illumination")
	private java.lang.Boolean illumination;

	@org.kie.api.definition.type.Label("buzzer")
	private java.lang.Boolean buzzer;

	@org.kie.api.definition.type.Label("fiveDot")
	private Boolean fiveDot;

	public FixtureConfiguration() {
	}

	public java.lang.Boolean getBacklight() {
		return this.backlight;
	}

	public void setBacklight(java.lang.Boolean backlight) {
		this.backlight = backlight;
	}

	public java.lang.String getButtonColor() {
		return this.buttonColor;
	}

	public void setButtonColor(java.lang.String buttonColor) {
		this.buttonColor = buttonColor;
	}

	public java.lang.String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(java.lang.String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public java.lang.String getFixtureType() {
		return this.fixtureType;
	}

	public void setFixtureType(java.lang.String fixtureType) {
		this.fixtureType = fixtureType;
	}

	public java.lang.Boolean getHairlineInsert() {
		return this.hairlineInsert;
	}

	public void setHairlineInsert(java.lang.Boolean hairlineInsert) {
		this.hairlineInsert = hairlineInsert;
	}

	public java.lang.Boolean getLetterRaised() {
		return this.letterRaised;
	}

	public void setLetterRaised(java.lang.Boolean letterRaised) {
		this.letterRaised = letterRaised;
	}

	public java.lang.Boolean getBraille() {
		return this.braille;
	}

	public void setBraille(java.lang.Boolean braille) {
		this.braille = braille;
	}

	public java.lang.Boolean getIllumination() {
		return this.illumination;
	}

	public void setIllumination(java.lang.Boolean illumination) {
		this.illumination = illumination;
	}

	public java.lang.Boolean getBuzzer() {
		return this.buzzer;
	}

	public void setBuzzer(java.lang.Boolean buzzer) {
		this.buzzer = buzzer;
	}

	public java.lang.Boolean getFiveDot() {
		return this.fiveDot;
	}

	public void setFiveDot(java.lang.Boolean fiveDot) {
		this.fiveDot = fiveDot;
	}

	public FixtureConfiguration(java.lang.Boolean backlight,
                                java.lang.String buttonColor, java.lang.String fixtureFamily,
                                java.lang.String fixtureType, java.lang.Boolean hairlineInsert,
                                java.lang.Boolean letterRaised, java.lang.Boolean braille,
                                java.lang.Boolean illumination, java.lang.Boolean buzzer,
                                java.lang.Boolean fiveDot) {
		this.backlight = backlight;
		this.buttonColor = buttonColor;
		this.fixtureFamily = fixtureFamily;
		this.fixtureType = fixtureType;
		this.hairlineInsert = hairlineInsert;
		this.letterRaised = letterRaised;
		this.braille = braille;
		this.illumination = illumination;
		this.buzzer = buzzer;
		this.fiveDot = fiveDot;
	}

}