package ch.welld.schindler.fixture.droolsknowledge.components.buzzers;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BuzzerConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private java.lang.String buzzerType;

	private java.lang.String fixtureFamily;

	public BuzzerConfiguration() {
	}

	public java.lang.String getBuzzerType() {
		return this.buzzerType;
	}

	public void setBuzzerType(java.lang.String buzzerType) {
		this.buzzerType = buzzerType;
	}

	public java.lang.String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(java.lang.String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public BuzzerConfiguration(java.lang.String buzzerType,
							   java.lang.String fixtureFamily, java.lang.String cableType) {
		this.buzzerType = buzzerType;
		this.fixtureFamily = fixtureFamily;
		this.cableType = cableType;
	}

}