package ch.welld.schindler.fixture.droolsknowledge.components.buzzers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BuzzerConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String buzzerType;

	private java.lang.String fixtureFamily;

	public BuzzerConfiguration() {
	}

	public java.lang.String getBuzzerType() {
		return this.buzzerType;
	}

	public void setBuzzerType(java.lang.String buzzerType) {
		this.buzzerType = buzzerType;
	}

	public java.lang.String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(java.lang.String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public BuzzerConfiguration(java.lang.String buzzerType, java.lang.String fixtureFamily) {
		this.buzzerType = buzzerType;
		this.fixtureFamily = fixtureFamily;
	}

}