package ch.welld.schindler.fixture.droolsknowledge.components.fixtures;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FixtureConfiguration implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean backlight;

	private java.lang.String buttonColor;

	private java.lang.String fixtureFamily;

	private java.lang.String fixtureSubfamily;

	private java.lang.String fixtureType;

	private java.lang.Boolean hairlineInsert;

	private java.lang.Boolean letterRaised;

	private java.lang.Boolean braille;

	private java.lang.Boolean illumination;

	private java.lang.Boolean buzzer;

	private Boolean fiveDot;

	private java.lang.String label;

	private java.lang.String doorButtonType;

	private java.lang.String pushType;

	public FixtureConfiguration() {
	}

	public java.lang.Boolean getBacklight() {
		return this.backlight;
	}

	public void setBacklight(java.lang.Boolean backlight) {
		this.backlight = backlight;
	}

	public java.lang.String getButtonColor() {
		return this.buttonColor;
	}

	public void setButtonColor(java.lang.String buttonColor) {
		this.buttonColor = buttonColor;
	}

	public java.lang.String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(java.lang.String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public java.lang.String getFixtureSubfamily() {
		return this.fixtureSubfamily;
	}

	public void setFixtureSubfamily(java.lang.String fixtureSubfamily) {
		this.fixtureSubfamily = fixtureSubfamily;
	}

	public java.lang.String getFixtureType() {
		return this.fixtureType;
	}

	public void setFixtureType(java.lang.String fixtureType) {
		this.fixtureType = fixtureType;
	}

	public java.lang.Boolean getHairlineInsert() {
		return this.hairlineInsert;
	}

	public void setHairlineInsert(java.lang.Boolean hairlineInsert) {
		this.hairlineInsert = hairlineInsert;
	}

	public java.lang.Boolean getLetterRaised() {
		return this.letterRaised;
	}

	public void setLetterRaised(java.lang.Boolean letterRaised) {
		this.letterRaised = letterRaised;
	}

	public java.lang.Boolean getBraille() {
		return this.braille;
	}

	public void setBraille(java.lang.Boolean braille) {
		this.braille = braille;
	}

	public java.lang.Boolean getIllumination() {
		return this.illumination;
	}

	public void setIllumination(java.lang.Boolean illumination) {
		this.illumination = illumination;
	}

	public java.lang.Boolean getBuzzer() {
		return this.buzzer;
	}

	public void setBuzzer(java.lang.Boolean buzzer) {
		this.buzzer = buzzer;
	}

	public java.lang.Boolean getFiveDot() {
		return this.fiveDot;
	}

	public void setFiveDot(java.lang.Boolean fiveDot) {
		this.fiveDot = fiveDot;
	}

	public java.lang.String getLabel() {
		return this.label;
	}

	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public java.lang.String getDoorButtonType() {
		return this.doorButtonType;
	}

	public void setDoorButtonType(java.lang.String doorButtonType) {
		this.doorButtonType = doorButtonType;
	}

	public java.lang.String getPushType() {
		return this.pushType;
	}

	public void setPushType(java.lang.String pushType) {
		this.pushType = pushType;
	}

	public FixtureConfiguration(java.lang.Boolean backlight,
								java.lang.String buttonColor, java.lang.String fixtureFamily,
								java.lang.String fixtureSubfamily, java.lang.String fixtureType,
								java.lang.Boolean hairlineInsert, java.lang.Boolean letterRaised,
								java.lang.Boolean braille, java.lang.Boolean illumination,
								java.lang.Boolean buzzer, java.lang.Boolean fiveDot,
								java.lang.String label, java.lang.String doorButtonType,
								java.lang.String pushType) {
		this.backlight = backlight;
		this.buttonColor = buttonColor;
		this.fixtureFamily = fixtureFamily;
		this.fixtureSubfamily = fixtureSubfamily;
		this.fixtureType = fixtureType;
		this.hairlineInsert = hairlineInsert;
		this.letterRaised = letterRaised;
		this.braille = braille;
		this.illumination = illumination;
		this.buzzer = buzzer;
		this.fiveDot = fiveDot;
		this.label = label;
		this.doorButtonType = doorButtonType;
		this.pushType = pushType;
	}

}