package ch.welld.schindler.fixture.droolsknowledge.components.mounting;

rule "LOP Mounting"
    when
        MountingConfiguration( componentType == "LOP" )
    then
end

rule "LIP Mounting"
    when
        MountingConfiguration( componentType == "LIP" )
    then
end

rule "LOP-K Mounting"
    when
        MountingConfiguration( componentType == "LOP-K" )
    then
end

rule "LOP-L Mounting"
    when
        MountingConfiguration( componentType == "LOP-L" )
    then
end

rule "Sealing Foam"
    when
        SealingFoamConfiguration ()
    then
end