package ch.welld.schindler.fixture.droolsknowledge.materials;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Family implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private String familyCode;
    private String pricePosition;
    private Map<String, Object> metadata;
    private Integer quantity = 1;

    public Family() {
    }

    public String getFamilyCode() {
        return this.familyCode;
    }

    public void setFamilyCode(String familyCode) {
        this.familyCode = familyCode;
    }

    public String getPricePosition() {
        return this.pricePosition;
    }

    public void setPricePosition(String pricePosition) {
        this.pricePosition = pricePosition;
    }

    public Map<String, Object> getMetadata() {
        return this.metadata;
    }

    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity == null ? 1 : quantity;
    }

    public Family(String familyCode, String pricePosition, Map<String, Object> metadata, Integer quantity) {
        this.familyCode = familyCode;
        this.pricePosition = pricePosition;
        this.metadata = metadata;
        this.quantity = quantity == null ? 1 : quantity;
    }
}