package ch.welld.schindler.fixture.droolsknowledge.materials;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Family implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String familyCode;
    private java.lang.String pricePosition;
    private java.util.Map<java.lang.String, java.lang.Object> metadata;

    public Family() {
    }

    public java.lang.String getFamilyCode() {
        return this.familyCode;
    }

    public void setFamilyCode(java.lang.String familyCode) {
        this.familyCode = familyCode;
    }

    public java.lang.String getPricePosition() {
        return this.pricePosition;
    }

    public void setPricePosition(java.lang.String pricePosition) {
        this.pricePosition = pricePosition;
    }

    public java.util.Map<java.lang.String, java.lang.Object> getMetadata() {
        return this.metadata;
    }

    public void setMetadata(java.util.Map<java.lang.String, java.lang.Object> metadata) {
        this.metadata = metadata;
    }

    public Family(java.lang.String familyCode, java.lang.String pricePosition, java.util.Map<java.lang.String, java.lang.Object> metadata) {
        this.familyCode = familyCode;
        this.pricePosition = pricePosition;
        this.metadata = metadata;
    }

}