package ch.welld.schindler.fixture.droolsknowledge.materials;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Material implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("materialCode")
	private java.lang.String materialCode;
	@org.kie.api.definition.type.Label("familyCode")
	private java.lang.String familyCode;

	@org.kie.api.definition.type.Label(value = "metadata")
	private java.util.Map<java.lang.String, java.lang.Object> metadata;

	public Material() {
	}

	public java.lang.String getMaterialCode() {
		return this.materialCode;
	}

	public void setMaterialCode(java.lang.String materialCode) {
		this.materialCode = materialCode;
	}

	public java.lang.String getFamilyCode() {
		return this.familyCode;
	}

	public void setFamilyCode(java.lang.String familyCode) {
		this.familyCode = familyCode;
	}

	public java.util.Map<java.lang.String, java.lang.Object> getMetadata() {
		return this.metadata;
	}

	public void setMetadata(java.util.Map<java.lang.String, java.lang.Object> metadata) {
		this.metadata = metadata;
	}

	public Material(java.lang.String materialCode, java.lang.String familyCode,
			java.util.Map<java.lang.String, java.lang.Object> metadata) {
		this.materialCode = materialCode;
		this.familyCode = familyCode;
		this.metadata = metadata;
	}

}