package ch.welld.schindler.fixture.droolsknowledge.components.lamps;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;
import ch.welld.schindler.fixture.droolsknowledge.components.NullableBoolean;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LampConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean en8120;

	private java.lang.String lamp;

	private java.lang.String fixtureFamily;

	private NullableBoolean copIntercomStation;

	private NullableBoolean doppelDeckerCar;

	public LampConfiguration() {
	}

	public java.lang.Boolean getEn8120() {
		return this.en8120;
	}

	public void setEn8120(java.lang.Boolean en8120) {
		this.en8120 = en8120;
	}

	public java.lang.String getLamp() {
		return this.lamp;
	}

	public void setLamp(java.lang.String lamp) {
		this.lamp = lamp;
	}

	public java.lang.String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(java.lang.String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public NullableBoolean getCopIntercomStation() {
		return copIntercomStation;
	}

	public void setCopIntercomStation(NullableBoolean copIntercomStation) {
		this.copIntercomStation = copIntercomStation;
	}

	public NullableBoolean getDoppelDeckerCar() {
		return doppelDeckerCar;
	}

	public void setDoppelDeckerCar(NullableBoolean doppelDeckerCar) {
		this.doppelDeckerCar = doppelDeckerCar;
	}

	public LampConfiguration(java.lang.Boolean en8120, java.lang.String lamp,
							 java.lang.String fixtureFamily) {
		this.en8120 = en8120;
		this.lamp = lamp;
		this.fixtureFamily = fixtureFamily;
	}
}