package ch.welld.schindler.fixture.droolsknowledge.components.lamps;

import ch.welld.schindler.fixture.droolsknowledge.builders.BaseConfiguration;
import ch.welld.schindler.fixture.droolsknowledge.components.NullableBoolean;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LampConfiguration extends BaseConfiguration {

	static final long serialVersionUID = 1L;

	private Boolean en8120;

	private String lamp;

	private String fixtureFamily;

	private NullableBoolean copIntercomStation;

	private NullableBoolean doppelDeckerCar;

	private String position;

	public LampConfiguration() {
	}

	public Boolean getEn8120() {
		return this.en8120;
	}

	public void setEn8120(Boolean en8120) {
		this.en8120 = en8120;
	}

	public String getLamp() {
		return this.lamp;
	}

	public void setLamp(String lamp) {
		this.lamp = lamp;
	}

	public String getFixtureFamily() {
		return this.fixtureFamily;
	}

	public void setFixtureFamily(String fixtureFamily) {
		this.fixtureFamily = fixtureFamily;
	}

	public NullableBoolean getCopIntercomStation() {
		return copIntercomStation;
	}

	public void setCopIntercomStation(NullableBoolean copIntercomStation) {
		this.copIntercomStation = copIntercomStation;
	}

	public NullableBoolean getDoppelDeckerCar() {
		return doppelDeckerCar;
	}

	public void setDoppelDeckerCar(NullableBoolean doppelDeckerCar) {
		this.doppelDeckerCar = doppelDeckerCar;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public LampConfiguration(
		Boolean en8120,
		String lamp,
	 	String fixtureFamily,
		String position
	) {
		this.en8120 = en8120;
		this.lamp = lamp;
		this.fixtureFamily = fixtureFamily;
		this.position = position;
	}
}